version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Port zewnętrzny dostępny dla użytkowników
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - adminservice

  frontend:
    build: ./front-end
    expose:
      - "3000"  # Port wewnętrzny, widoczny dla Nginx
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "5000"  # Port wewnętrzny, widoczny dla Nginx
    depends_on:
      - db
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@db:5432/conference
      - SECRET_KEY=wojciechsecret

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conference
    volumes:
      - db_data:/var/lib/postgresql/data

  adminservice:
    build: ./adminservice
    command: sh -c "daphne -b 0.0.0.0 -p 8000 adminservice.asgi:application"
    expose:
      - "8000"  # Port wewnętrzny, widoczny dla Nginx
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conference
      POSTGRES_HOST: db

volumes:
  db_data:
